### PR TITLE
Added WIP C++ installer

### PR DESCRIPTION
**Pull request by bolt926**

### CODE REVIEW

**Comment by polandlover123** [comment]
lemme try

**Comment by caernarferon** [comment]
@spacefault look at this

**Review by spacefault — APPROVED** [review]
seems good, any thoughts? @caernarferon

**Comment by polandlover123** [comment]
> seems good, any thoughts? @caernarferon

one moment

**Review by spacefault — COMMENTED** [review]
It seems good

**Review by spacefault — APPROVED** [review]
approved

**Comment by spacefault** [comment]
Closed due to unverified commits. Original contributor has agreed to make a new PR with verified commits.

**Pull request closed without merging**
