### PR TITLE
INCOMPLTE installer-v2 implementation

### PR DESCRIPTION
**Pull request by spacefault**
This PR merges an incomplete implementation of the new installer-v2 framework. It's now been rewritten in C++ (thanks to @bolt926!), and has newer features. This PR mostly contains improvements to bolt926's installer-v2 implementation, and a finished framework is coming soon.

### CODE REVIEW

**Comment by polandlover123** [comment]
bing chilling.

**Comment by xMqme** [comment]
yes

**Comment by bolt926** [comment]
Seems good to me.

**Review by polandlover123 — APPROVED** [review]
it works on my machine 🤓

**Comment by spacefault** [comment]
Closing this pull request, I will make a new one when installer-v2 is done.

**Comment by polandlover123** [comment]
DRAFT

**Pull request closed without merging**
